apiVersion: v1
kind: Secret
metadata:
  name: my-argocd-poc-sg-app-1
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: my-argocd-poc-sg-app-1
  url: https://github.com/Tsuweiquan/my-argocd-poc-sg-app-1.git
  project: singapore
